import type { Metadata } from "next";
import { rubik } from "@/app/ui/fonts";
import "@/app/globals.css";
import Navbar from "@/app/ui/navbar";
import Footer from "@/app/ui/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <title>TuneHub</title>
      <body className={rubik.className}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
