import type { Metadata } from "next";
import { rubik } from "@/app/ui/fonts";
import "@/app/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <title>TuneHub</title>
      <body className={rubik.className}>
        {children}
        <script src="https://kit.fontawesome.com/49b78285c5.js" crossOrigin="anonymous"></script>
      </body>
    </html>
  );
}

